//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvSitesiAsp.Net_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLHAKKIMDA
    {
        public int ID { get; set; }
        public string Bilgiler { get; set; }
        public string Egitim { get; set; }
        public string İsDeneyimleri { get; set; }
    }
}
